import webbrowser
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
webbrowser.open('https://youtube.com/flamingo')
webbrowser.open('https://twitter.com/Albertsstuff')
webbrowser.open('https://instagram.com/Albertsstuff')
webbrowser.open('https://youtooz.com/flamingo')
my_file = open("flamingo2.txt","w+")
my_file.write("sucribe falingo")
my_file = open("flamingo3.txt","w+")
my_file.write("sucribe falingo")
my_file = open("flamingo4.txt","w+")
my_file.write("sucribe falingo")
my_file = open("flamingo5.txt","w+")
my_file.write("sucribe falingo")
my_file = open("flamingo6.txt","w+")
my_file.write("sucribe falingo")
my_file = open("nob.txt","w+")
my_file.write("BIG NOB HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA")
my_file = open("you.txt","w+")
my_file.write("BIG NOB HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA")
my_file = open("sure.txt","w+")
my_file.write("BIG NOB HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA")
my_file = open("are.txt","w+")
my_file.write("BIG NOB HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA")
Join = input('are you on vm')
import urllib.request
if Join.lower() == 'yes':
    my_file = open("vm_user.txt","w+")
    my_file.write("you vm user................................................... who are you")
else:
    my_file = open("OH_SHIT.txt","w+")
    my_file.write("oh FUCK you're stupid... commit sucribe falingo")
    my_file = open("HAHAHAHA.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA1.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA2.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA3.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA4.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA5.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA6.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA7.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHA8.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    my_file = open("HAHAHAHAHAHA.txt","w+")
    my_file.write("commit sucribe falingo you're perfect candidate.. big nob small brain")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
    urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945228465831997/Png.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
urllib.request.urlretrieve("https://media.discordapp.net/attachments/709844315362426990/712945782852026368/htt.png")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
my_file = open("WHO HERE LOVES PAW PATROL.txt","w+")
my_file.write("WHO HERE LOVES PAW PATROL")
